### ISSUE TITLE
Move all lambda functions to use Graviton2 for cost optimisation

### ISSUE THREAD

**Issue by stationeros** [intuit/Trapheus#122]
Our lambda function defintion from here https://github.com/intuit/Trapheus/blob/master/template.yaml#L178C24-L178C24 needs to be moved to Graviton, 

Lambda offers two [instruction set architectures](https://docs.aws.amazon.com/lambda/latest/dg/foundation-arch.html) in most AWS Regions: x86 and arm64.  Lambda functions powered by Graviton2 are designed to deliver up to 19 percent better performance at 20 percent lower cost.

We should move our functions to explicityly use Graviton2 (see example below)

```
MyFunction:
  Type: AWS::Serverless::Function
  Properties:
    Architectures:
      - arm64  #  use Graviton2
      -
````
